### ISSUE TITLE
IBRNet: Learning Multi-View Image-Based Rendering

### ISSUE THREAD

**Issue by seriousran** [Pseudo-Lab/nerds-nerf#2]

**Comment by parkjh688** [comment]
논문 발표 끝났고 영상 및 슬라이드 업로드 하였습니다!

- 논문 링크 : https://arxiv.org/pdf/2102.13090.pdf
- 슬라이드 링크 : https://drive.google.com/file/d/1g1QpZoPE-bbpIw9DJWVwilwQhUCC0zpY/view?usp=share_link
